### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by HuXiaoJie** [ddnlink/ddn#128]
mac 11.5.2
npm 6.9.0
node 10.21.0

我下载的dev版本运行
npm install 然后又倒入了ddn下的peer,core包
npm start

localhost:ddn-dev jerome$ npm start

> ddn@3.6.3 start /Users/jerome/workpath/VScode/ddn-dev
> NODE_ENV=development node ./scripts/startPeer.js

Start dev blockchain for /Users/jerome/workpath/VScode/ddn-dev/scripts/node
(node:86553) [SEQUELIZE0003] DeprecationWarning: String based operators are deprecated. Please use Symbol based operators for better security, read more at https://sequelize.org/master/manual/querying.html#operators
Executing (default): SELECT 1+1 AS result
info 08:16:53.51 loader.js:171 () @ddn/asset-evidence 资产包不包含自定义数据模型内容。
info 08:16:53.51 loader.js:171 () @ddn/asset-dapp 资产包不包含自定义数据模型内容。
Error: Sandbox is not ready
    at oe (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:9463)
    at b.value (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:109497)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:109598)
    at Generator.next (<anonymous>)
    at x (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1128)
    at s (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1331)
    at /Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1390
    at new Promise (<anonymous>)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1271)
    at b.L.value (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:109720)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:106539)
    at Generator.next (<anonymous>)
    at x (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1128)
    at s (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1331)
    at /Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1390
    at new Promise (<anonymous>)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1271)
    at b.L.value (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:106727)
    at Program.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/peer/lib/kernal/program.js:221:43)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/peer/lib/kernal/program.js:144:103)
    at _next (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/peer/lib/kernal/program.js:146:194)
Error: Sandbox is not ready
    at oe (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:9463)
    at b.value (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:109497)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:109598)
    at Generator.next (<anonymous>)
    at x (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1128)
    at s (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1331)
    at /Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1390
    at new Promise (<anonymous>)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1271)
    at b.L.value (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:109720)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:106539)
    at Generator.next (<anonymous>)
    at x (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1128)
    at s (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1331)
    at /Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1390
    at new Promise (<anonymous>)
    at b.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:1271)
    at b.L.value (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/contract/dist/index.js:1:106727)
    at Program.<anonymous> (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/peer/lib/kernal/program.js:221:43)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/peer/lib/kernal/program.js:144:103)
    at _next (/Users/jerome/workpath/VScode/ddn-dev/node_modules/@ddn/peer/lib/kernal/program.js:146:194)
info 08:16:53.98 program.js:366 (process.once) process exited

**Comment by HuXiaoJie** [comment]
error yargs@17.1.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.21.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Waiting for the debugger to disconnect...
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'ddn'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'ddn'
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ddn@3.6.3 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ddn@3.6.3 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Applications/MxSrvs/cache/nodejs/_logs/2021-09-07T00_48_41_898Z-debug.log
Waiting for the debugger to disconnect...

**Comment by cnTailor** [comment]
# ddn dev 环境搭建：
## 一. 安装构建工具
1. npm install -g yarn
2. npm install -g lerna
## 二. 源码安装
1. git clone https://github.com/ddnlink/ddn.git
2. lerna bootstrap
3. cd ddn
4. yarn build
5. cd ddn/examples/fun-tests
6. yarn start
## 三. 说明
1. ddn基于node v10.21.0编译运行,任何要求10以上的node版本可能无法正常运行
2. ddn对所依赖的包已经做了限制（版本号都是以^开头)，但所依赖的包依赖的包未必有限制，所以导致yarns安装v17*的版本。我们无法更改所依赖包的内容，你可以自行修改该包的依赖；或者，使用我们提供的yarn.lock文件，我们提交了yarn.lock文件，请git pull获取。然后运行 yarn
3. 或者，您可以挑战更高的node版本，这可能导致一些原生包的编译问题，需要您一一尝试解决。

**Comment by cnTailor** [comment]
初次接触源码，此类问题可能较常见，次问题保持打开

**Comment by imfly** [comment]
欢迎在新的node版本下偿试修改并提交您的PR

**Comment by HuXiaoJie** [comment]
公链运行起来之后 钱在哪个地址放着? 这个地址的密码是多少?这个找不到 想往出转帐没有密码转不了

**Comment by HuXiaoJie** [comment]
或者说公链运行起来之后  这个币需要怎么操作才能转出来

**Comment by cnTailor** [comment]
自行搭建运行私有链时，应该通过ddn命令行生成创世区块，这样创世私钥你就可以看到。具体生成方法，ddn官网文档有说明：https://docs.ddn.net/zh-CN/guide/ddn-cli

在 2021-09-09 18:13:40，"HuXiaoJie" ***@***.***> 写道：

或者说公链运行起来之后 这个币需要怎么操作才能转出来

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
